### ISSUE TITLE
Fixing modal in FormPage

### ISSUE THREAD

**Issue by SamuelPelletierEvraire** [ai-cfia/fertiscan-frontend#116]
This issue is regrouping 4 issues related to the modal on the FormPage

- [x]  https://github.com/ai-cfia/fertiscan-frontend/issues/111
- [x] https://github.com/ai-cfia/fertiscan-frontend/issues/110
- [x] https://github.com/ai-cfia/fertiscan-frontend/issues/115
- [x] https://github.com/ai-cfia/fertiscan-frontend/issues/120
