### ISSUE TITLE
Remove yellow (Modify) feature and add blue iscurrentlymodified***

### ISSUE THREAD

**Issue by Youllou** [ai-cfia/fertiscan-frontend#131]
# Description
Any progressbar section has, at this time, 4 states
- Default (grey)
- Validated (green)
- Modifying (Yellow)
- Rejected (Red)
The Modifying state isnt really relevant and should be the same as the default one.
On top of that it would be nice to indicate clearly to the user where they currently are. We would then add a blue state that is only on one section at a time showing which section the user has currently focussed

# Task
- [x] Replace the modifying state by the default one
- [x] Add a CurrentlyModifying state that makes the focused section appear blue on the progressbar

# Acceptance criteria
- [x] There is no more yellow section on the progressbar
- [x] When a section passes from validated to modifying, the corresponding section on the progressbar appears grey
- [x] The section focused by the use appears blue on the progressbar
- [x] No other section appears blue on the progressbar
