### ISSUE TITLE
(Refactor) Determination of the code positioning structure.

### ISSUE THREAD

**Issue by SamuelPelletierEvraire** [ai-cfia/fertiscan-frontend#190]
# Description:
This task entails creating a streamline and enforce a consistent code positioning structure within the FertiScan project to optimize code organization and facilitate navigation and maintenance. The task requires the creation of a set of standards outlining the structured layout of code blocks, modules, and classes within the codebase.

## Task

- [ ] Schedule a meeting with FertiScan frontend team to talk about this topic.
- [ ] Creation of codePositioningConvention.md.
- [ ] New GitHub check created for the code positioning convention compliance.

## Acceptance criteria

- [ ] The documentation must be precise and cover all use cases.
- [ ] Any new case not present in the documentation must be added before the `useEffect` hooks / event listeners.

### Parent task
**Ensure that all prerequisite or parent tasks are completed before commencing this task.**
#189

### Child tasks
**Next task to do**
#18

**Comment by SamuelPelletierEvraire** [comment]
Here is the workflow file for testing this (Please notice that this is a draft version of the GitHub workflow and needs to be optimized:
```
const fs = require('fs');
const parser = require('@babel/parser');
const traverse = require('@babel/traverse').default;
const glob = require('glob');

const projectPath = 'src'; // Replace with the appropriate directory for your project
const filePattern = `${projectPath}/**/*.{ts,tsx}`;

function reportError(node, message, filePath) {
  const location = node.loc.start;
  console.error(`${filePath}:${location.line}:${location.column} - ${message}`);
}

function checkFile(filePath) {
  const content = fs.readFileSync(filePath, 'utf-8');
  const ast = parser.parse(content, {
    sourceType: 'module',
    plugins: [
      'jsx',
      'typescript', // Enable TypeScript plugin
      'classProperties',
      'decorators-legacy',
      'dynamicImport',
    ],
  });

  let state = {
    hasImports: false,
    hasExports: false,
    hasConstants: false,
    hasTypes: false,
    hasInterfaces: false,
    hasEnums: false,
    hasHelperFunctions: false,
    hasCustomHooks: false,
    hasReactComponent: false,
    insideReactComponent: false,
    hasPropTypes: false,
    hasDefaultProps: false,
    // You can add other states here based on your structure
  };

  traverse(ast, {
    // Import statements
    ImportDeclaration(path) {
      if (state.hasConstants || state.hasTypes || state.hasInterfaces || state.hasEnums || state.hasHelperFunctions || state.hasCustomHooks || state.hasReactComponent) {
        reportError(path.node, 'Import declarations should come first.');
      }
      state.hasImports = true;
    },
    // Type aliases
    TSTypeAliasDeclaration(path) {
      if (state.hasInterfaces || state.hasEnums || state.hasHelperFunctions || state.hasCustomHooks || state.hasReactComponent) {
        reportError(path.node, 'Type aliases must be declared after import statements and before interfaces, enums, and functions.');
      }
      state.hasTypes = true;
    },
    // Interfaces
    TSInterfaceDeclaration(path) {
      if (state.hasEnums || state.hasHelperFunctions || state.hasCustomHooks || state.hasReactComponent) {
        reportError(path.node, 'Interfaces must be declared after type aliases and before enums, functions, and the React component.');
      }
      state.hasInterfaces = true;
    },
    // Enums
    TSEnumDeclaration(path) {
      if (state.hasHelperFunctions || state.hasCustomHooks || state.hasReactComponent) {
        reportError(path.node, 'Enums must be declared after type aliases, interfaces, and before functions and the React component.');
      }
      state.hasEnums = true;
    },
    // Custom hooks (assuming an arrow function starting with "use" is a hook)
    ArrowFunctionExpression(path) {
      if (path.get('id') && /^[use[A-Z0-9]].*$/.test(path.get('id').node.name)) {
        if (!state.hasReactComponent) {
          state.hasCustomHooks = true;
        } else {
          reportError(path.node, 'Custom hooks should be declared before the React component.');
        }
      }
    },
    // React component (assuming a function/capitalized variable is a component)
    'FunctionDeclaration|ArrowFunctionExpression|FunctionExpression|VariableDeclaration'(path) {
      const isComponentFunction = path.isFunctionDeclaration() ||
        (path.isFunctionExpression() && path.parentPath.isVariableDeclarator() && /^[A-Z]/.test(path.parentPath.get('id').node.name)) ||
        (path.isVariableDeclaration() && path.get('declarations.0.id').node.name.match(/^[A-Z]/));

 if (isComponentFunction && !state.insideReactComponent) {
    if (state.hasReactComponent || state.hasExports) {
      reportError(path.node, 'Only one main React component should be declared per file.');
    } else {
      // Enter the React component
      state.hasReactComponent = true;
      state.insideReactComponent = true;

path.traverse({
  // Entering a function expression or arrow function that could represent a hook or handler
  'FunctionExpression|ArrowFunctionExpression'(innerPath) {
    // Differentiate between hooks and handlers based on naming convention
    const functionName = innerPath.parentPath.node.id && innerPath.parentPath.node.id.name;
    if (functionName && /^use[A-Z]/.test(functionName)) {
      // Detected a hook
      if (state.hasHandlers || state.hasConditionalRender || state.hasReturn) {
        reportError(innerPath.node, 'Hooks should be defined at the top of the component, before handlers and render logic.', filePath);
      }
      // Perform further checks or parsing on the hook function
      // parseReactHook(innerPath);
    } else if (functionName && /^handle[A-Z]/.test(functionName)) {
      // Detected a handle function
      if (!state.hasHooks) {
        reportError(innerPath.node, 'Handlers should be defined after hooks.', filePath);
      } else if (state.hasConditionalRender || state.hasReturn) {
        reportError(innerPath.node, 'Handlers should be defined before render logic and return statement.', filePath);
      }
      state.hasHandlers = true;
      // Perform further checks or parsing on the handler function
      // parseHandlerFunction(innerPath);
    }
  },
  // Parsing JSX Elements for conditional rendering logic
  JSXElement(innerPath) {
    if (!state.hasReturn) {
      // We are in the render logic portion
      state.hasConditionalRender = true;
      // Add checks related to JSX here if needed
      // parseJsxElement(innerPath);
    } else {
      // If we've hit JSX after a return statement, there's a structural error
      reportError(innerPath.node, 'No additional JSX should be defined after the return statement.', filePath);
    }
  },
  // Return statement should be the last part of the component
  ReturnStatement(innerPath) {
    if (state.hasReturn) {
      // Only one return statement is typical for a functional React component
      reportError(innerPath.node, 'Multiple return statements detected. Only one return statement is expected in a component.', filePath);
    } else {
      state.hasReturn = true;
      // No additional parsing may be required for the return statement, but you could add it if necessary
      // parseReturnStatement(innerPath);
    }
  },
  exit(innerPath) {
    if (innerPath === path) {
      // Exiting the main component function
      // Ensure all required structure is present
      if (!state.hasHooks) {
        console.warn(`Warning: No hooks found. If this component uses hooks, they should be defined before handlers and render logic.`);
      }
      if (!state.hasHandlers) {
        console.warn(`Warning: No handler functions found. It's possible this component does not contain event handlers.`);
      }
      if (!state.hasConditionalRender) {
        console.warn(`Warning: No render logic found. If this component produces JSX, it should contain render logic.`);
      }
      if (!state.hasReturn) {
        reportError(innerPath.node, 'No return statement found in the component.', filePath);
      }
    }
  },
});
        }
      } else if (state.insideReactComponent && path.isReturnStatement()) {
        state.insideReactComponent = false; // Exit the component when we hit the return statement
      }
    },
    // Export statements
    'ExportNamedDeclaration|ExportDefaultDeclaration'(path) {
      state.hasExports = true;
    },
  });

  console.log(`File ${filePath} checked.`);
}

// Use glob to find all .ts and .tsx files in the project
glob(filePattern, (err, files) => {
  if (err) {
    console.error('Error finding files in project:', err);
    return;
  }

  files.forEach(checkFile);
});

console.log('React project structure check completed.');
```

###  Installation needed:

`npm install --save-dev @babel/core @babel/parser @babel/traverse`
`npm install glob`

### For executing the script

`node check_code_structure.js`

### For testing the workflow

[BadComponent.txt](https://github.com/user-attachments/files/16459890/BadComponent.txt)
[GoodComponent.txt](https://github.com/user-attachments/files/16459900/GoodComponent.txt)

**Comment by Endlessflow** [comment]
@ai-cfia/devops what do you guys think ? Does this seem like something we can

**Comment by SamuelPelletierEvraire** [comment]
For import order, let's use the library [here](https://www.npmjs.com/package/eslint-plugin-import)
