### ISSUE TITLE
(Refactor) Creation and documentation of templates for elements used repeatedly.

### ISSUE THREAD

**Issue by SamuelPelletierEvraire** [ai-cfia/fertiscan-frontend#191]
# Description:
In the context of improving the codebase of the FertiScan app, it is crucial to establish a refactoring task focused on the creation and documentation of templates for elements that are used repeatedly throughout the application. This task aims to promote code reuse, maintain consistency, and expedite development by providing standardized templates for common UI components and code structures.

## Task

- [ ] Schedule a meeting with FertiScan frontend team to talk about this topic.
- [ ] Creation of codeTemplateDocumentation.md.
- [ ] Create the folder `componentTemplate`.
- [ ] Create a file for each template within the `componentTemplate` folder.

## Acceptance criteria

- [ ] The documentation must be precise and cover all template created.
- [ ] The documentation needs to include a list of the created templates at its beginning.
- [ ] Templates must be modular to allow for slight adjustments.

### Parent task

**Ensure that all prerequisite or parent tasks are completed before commencing this task.**
#190

### Child tasks

**Next task to do**
#192
