### ISSUE TITLE
(Refactor) Documentation of the pages accessible by phone.

### ISSUE THREAD

**Issue by SamuelPelletierEvraire** [ai-cfia/fertiscan-frontend#192]
# Description:

For the ongoing refactor of the FertiScan project, a detailed documentation of all pages that are accessible via phone (mobile devices) is required. The goal is to ensure that all team members have a thorough understanding of the mobile interface and its navigation, and to guarantee that the app’s mobile version remains user-friendly, cohesive, and fully functional.

## Task

- [ ] Schedule a meeting with FertiScan frontend team to talk about this topic.
- [ ] Creation of phonePageDocumentation.md.

## Acceptance criteria

- [ ] The documentation must be precise and cover all page accessible by phone.
- [ ] The documentation needs to include a list of those pages at its beginning.

### Parent task

**Ensure that all prerequisite or parent tasks are completed before commencing this task.**
#191

### Child tasks

**Next task to do**
#193

**Comment by SamuelPelletierEvraire** [comment]
## For documentation

For now, the only pages that should be available on the phone should be the page to take pictures in occurrence : CapturPage, And also the page to search if a fertiliser has already been inspected. SavedLabelList.

**Comment by SamuelPelletierEvraire** [comment]
Popup give option to continue to the form or return to the upload page. (Maybe some setting for not showing the popup anymore)
