### ISSUE TITLE
As a dev, I want to refactor the `header` component

### ISSUE THREAD

**Issue by SamuelPelletierEvraire** [ai-cfia/fertiscan-frontend#196]
## Description
Implement the new header.

## Prototype

![image](https://github.com/user-attachments/assets/593c7c40-4a88-469c-bae7-c31bf9d6ebfa)

### Header exemple:
<img src="https://github.com/user-attachments/assets/a43ff5dc-1afe-4438-bdd9-36f5cd8e145c" width="600">

## Tasks

Refactor the old header to the new header shown in this picture.

## Acceptance Criteria

- [x] Must contain the ACIA logo
- [x] Must contain a button to change language
- [x] Must contain a profile button [profile / dashboard page issue](https://github.com/ai-cfia/fertiscan-frontend/issues/283)
- [x] Must contain a button to display the side menu [side menu issue](https://github.com/ai-cfia/fertiscan-frontend/issues/197)

### Figma design (Please note that the dimension on the design are not accurate)
https://www.figma.com/design/wZAiODRsAfqa8cAxJtQAYr/Untitled?node-id=0-1&t=jbtVtLENKlvQoKjX-1

**Comment by k-allagbe** [comment]
According to this: https://github.com/ai-cfia/fertiscan-frontend/issues/248

![image](https://github.com/user-attachments/assets/e95255e0-357e-4a93-ad89-094675f11031)

We seem to need the banner.

**Comment by ChromaticPanic** [comment]
https://github.com/ai-cfia/fertiscan-frontend/issues/186#issuecomment-2426731157

**Comment by ChromaticPanic** [comment]
After catching up with William and looking at ServiceCFIA the current header is fine ![Image](https://github.com/user-attachments/assets/9beb2b5c-20ac-4db6-a630-c5491bc41118)

**Comment by SamuelPelletierEvraire** [comment]
Create new issue for separate user Popup and the header.: https://github.com/ai-cfia/fertiscan-frontend/issues/298
