### ISSUE TITLE
(Refactor) SideMenu

### ISSUE THREAD

**Issue by SamuelPelletierEvraire** [ai-cfia/fertiscan-frontend#197]
# Description
Initiate a restructuring and optimization effort of the SideMenu component within the FertiScan project. This task involves reimagining the component's functionality, look and feel, and adaptability to different screen sizes. Comprehensive documentation of the refactored component should be developed to facilitate maintenance and forward compatibility.

## Task

- [ ] Schedule a meeting with FertiScan frontend team to talk about this topic.
- [ ] Other task to be determined during the meeting.
- [ ] QA testing before merging.

## Acceptance criteria

- [ ] A SideMenu component that integrates effortlessly with the existing FertiScan app framework and is received positively by the development team.
- [ ] Clear and thorough documentation that enables effective handover to, and comprehension by, other developers.
- [ ] Confirmation by the QA testing that the new SideMenu provides a good user experience without any negative impact on existing functionalities.

### Parent task
**Ensure that all prerequisite or parent tasks are completed before commencing this task.**
#

### Child tasks
**Next task to do**
#

**Comment by SamuelPelletierEvraire** [comment]
@k-allagbe  @Francois-Werbrouck  @Youllou shoud we include a button for the dashboad as another way to access it ?

**Comment by k-allagbe** [comment]
Fine by me.
