### ISSUE TITLE
As a dev, I want to refactor the  `CapturPage` to `HomePage` component

### ISSUE THREAD

**Issue by SamuelPelletierEvraire** [ai-cfia/fertiscan-frontend#198]
## Description
Refactor the CapturPage

## Prototype
![image](https://github.com/user-attachments/assets/d4fb46b1-d277-400a-83ef-4e10188d3c7e)

## Tasks
Refactor the old capturPage to the page in this picture.

## Acceptance Criteria
Here's the translation of the list into English:

- [x] Must contain a section for drag and drop of documents.
- [ ] Should be able to receive folders to facilitate the import of multiple images.
- [ ] Should be able to receive PDF and extract the image of them. [here the exemple](https://codepen.io/TeoM/pen/abOzEor)
- [ ] The browse file button should allow importing images and folders.
- [ ] Each file contained within folders should be displayed as individual files.
- [ ] Only images will be taken from the folders.
- [ ] The display section for imported folders should contain a context menu with the options:
- Rename
- Delete
- Do not analyze (This third option should be coded but not displayed for the moment)
- [x] Image display should occur when the user over the thumbnail in the list of imported files.
- [ ] The submit button should not be visible if no images are imported.
- [x] The capturPage should be rename HomePage

**The original HomePage from before the refactor is use as a router and should become router.tsx**

### Figma design (Please note that the dimension on the design are not accurate)
https://www.figma.com/design/wZAiODRsAfqa8cAxJtQAYr/Untitled?node-id=0-1&t=jbtVtLENKlvQoKjX-1
