### ISSUE TITLE
As a dev, I want to refactor the `AlertBanner` Component

### ISSUE THREAD

**Issue by SamuelPelletierEvraire** [ai-cfia/fertiscan-frontend#199]
## Description
Use the design of MaterialUI alert banner [See documentation here](https://mui.com/material-ui/react-alert/#:~:text=to%20start%20editing-,Outlined,-This%20is%20an).

## Prototype

No figma design.

## Tasks
Refactor the current alert banner to use the one provided by MaterialUI.

## Acceptance Criteria

- [ ] The alert appear at the top and centred on the page.
- [ ] The alert appear for 5 second and after disappear with a slide animation to the top.
- [ ] The alert is related to the `AlertProvider` to make it modular (Approve alert and Error alert) [AlertProvider issue](https://github.com/ai-cfia/fertiscan-frontend/issues/194).
