### ISSUE TITLE
As a dev, I want to refactor the `ConfirmPage` Page

### ISSUE THREAD

**Issue by SamuelPelletierEvraire** [ai-cfia/fertiscan-frontend#202]
## Description
Refactor confirmation page
### ConfirmPage with the image carousel
![image](https://github.com/user-attachments/assets/81ae0861-c8b0-4332-a942-4bc63e2decd4)

### ConfirmPage with the reduced image carousel
![image](https://github.com/user-attachments/assets/47cb4198-311b-4dc6-9211-f787ad3886d8)

### ConfirmPage animation
![Animation confirmPage](https://github.com/user-attachments/assets/67811793-8a47-4fa6-b8fe-bd6207b65b90)

## Tasks
Refactor the old confirmation page.

## Acceptance Criteria

- [ ] The information of the label are displayed as it is show on the previous picture (Except the text size).
- [ ] Field are cliquable to go directly to the form section. A floating button replace the next button of the form section to go back directly to the confirm page.
- [ ] The default page for the ConfirmPage is the ConfirmPage with reduce carousel.
- [ ] The text format is enough big to be easily readable. 

### Figma design (Please note that the dimension on the design are not accurate)
https://www.figma.com/design/wZAiODRsAfqa8cAxJtQAYr/Untitled?node-id=0-1&t=jbtVtLENKlvQoKjX-1
