### ISSUE TITLE
As a dev, I want to refactor the user page call `DashboardPage` component.

### ISSUE THREAD

**Issue by SamuelPelletierEvraire** [ai-cfia/fertiscan-frontend#283]
## Description
Refactor the user information that wasn't include previously in the project

### Dashboard design
![image](https://github.com/user-attachments/assets/7b6ddb44-5d23-4b27-bd1b-0c509797c559)

### Header button to go to dashboard
![Header button to go to dashboard](https://github.com/user-attachments/assets/ae009100-cbcf-497b-ad0e-271f5bf25082)

### Animation on dashboard
![Animation dashboard page](https://github.com/user-attachments/assets/a4df6710-5259-48d4-a7e9-1bb3195c460c)

## Tasks
Implement the dashboard page for user information.

## Acceptance Criteria

- [ ] The page contain the inspector name (for now the username).
- [ ] The page contain the email address (Not show but coded for later).
- [ ] The page contain the role of the user (Not show but coded for later).
- [ ] The page contain the location of the inspector (For now this information is not include into our database).
- [ ] The page contain the number of inspection done by the user  (For now this information is not include into our database).
- [ ] The page contain inspections done and not finish by the user.
- [ ] The inspection not finished by the inspector appear at the top of the list of inspection and are identified with a badge.
- [ ] A search bar is integrated to search on the user inspection to facilitate the research if the inspection have a lot of inspection.
- [ ] Pagination is include if there are more than 10 inspection related to the user. (Not on the design so make sure to check with the team before designing it).
- [ ] The loading of the inspection are not made all in one request. They are made by pagination to reduce latency.
- [ ] When the user click on an element of the label list, the information page should appear showing the information of the label.

### Figma design (Please note that the dimension on the design are not accurate)
https://www.figma.com/design/wZAiODRsAfqa8cAxJtQAYr/Untitled?node-id=0-1&t=jbtVtLENKlvQoKjX-1

**Comment by SamuelPelletierEvraire** [comment]
@Francois-Werbrouck can it be possible to add this since it is not a sensitive data? (I need more data on user to full fill the dashboard page more professionally

> * [ ]  The page contain the location of the inspector (For now this information is not include into our database)

**Comment by SamuelPelletierEvraire** [comment]
@Francois-Werbrouck 

Can it be possible to include picture only for this page. The picture would be loaded by pagination request of 10 to reduce the the loading time. Since inspector would not have 2000 label on is account I thinks this would not be a big difference. Feel free to rectify me if this is not a good idea.

**Comment by Francois-Werbrouck** [comment]
>to put more information on the dashboard?

Yes but is it relevant information? (Number of inspection can be calculated easily)

----

>Can it be possible to include picture only for this page. 

Yes one of the 'restriction' we currently have is the picture are store inside the the user's container. We can easily fetch the user's own pictures.

I'm still uncertain about how we want to handle the pagination. Fetching the data from the DB is quicker in one go. However, loading the blobs (picture files) could be done by batch of 10.

I dont know about the best practice of pagination. There probably exists design pattern for such tasks.

----

>Can it be possible to add [the location of the user] since it is not a sensitive data? (I need more data on user to full fill the dashboard page more professionally

I mean, sure; However that means requiring the user to fill in that data when creating its account. We have no way of knowing the user's name, location, email, etc. if it isn't provided to us manually. I get you want the dashboad to look more "professional", but adding those field doesn't bring much value in the eyes of the Inspector nor does it bring value to our prototype. I'd leave displaying extra data for later on in the life cycle of our project.

**Comment by k-allagbe** [comment]
I agree with @Francois-Werbrouck. Let's keep in mind the objective of just giving a more professional look to what we currently have, without requiring too many more features or core data modification.
