### ISSUE TITLE
As a dev, I want to refactor the login / sign up component.

### ISSUE THREAD

**Issue by SamuelPelletierEvraire** [ai-cfia/fertiscan-frontend#284]
## Description
Refactor the login/sign up component.

### Login overlay:
![image](https://github.com/user-attachments/assets/7e4121d2-b5e9-4584-8720-b5449fb61c4f)

### Login error overlay:
![image](https://github.com/user-attachments/assets/9d749c2d-6582-4f53-b0a8-9b05df97395d)

### Sign up overlay:
![image](https://github.com/user-attachments/assets/c308af6b-960a-4558-b546-20652d3f4c0b)

## Tasks

Refactor the old login/sign up component that were combined in the `SettingPage` to two separate component overlay.

## Acceptance Criteria

- [x] The login is the first thing that appear and the user can access the homePage if not signIn
- [x] The login and the sign up component are two separate process.
- [x] The signup is not working if the checkbox is not checked.
- [x] The login appear in overlay of the `HomePage`.
- [x] The SignUp appear in overlay of the `HomePage`.
- [x] The username and password are verify by call to the backend.
- [x] An alert appear on the overlay if the credential are not valid.
- [x] The password and the confirm password field content are identical or else an error occur.
- [ ] When trying to sign up the username is check to make sure it is not already use.
- [x] When all check are approved the overlay disappear.

### Figma design (Please note that the dimension on the design are not accurate)
https://www.figma.com/design/wZAiODRsAfqa8cAxJtQAYr/Untitled?node-id=0-1&t=jbtVtLENKlvQoKjX-1
