### ISSUE TITLE
As a dev, I want to create a popup for user information

### ISSUE THREAD

**Issue by SamuelPelletierEvraire** [ai-cfia/fertiscan-frontend#298]
## Description
Implement the new menu / popup for user informations.

### Profile button :
<img src="https://github.com/user-attachments/assets/333431df-f937-432d-b41f-618be82c5f5b" width="400">

## Tasks

Add the new way to access the user dashboard.

## Acceptance Criteria

- [x] Must contain the Logout Button.
- [x] Must contain the username.
- [x] Must appear under the user icon button.
- [x]  Must contain the button to go to the Dashboard page

### Figma design (Please note that the dimension on the design are not accurate)
https://www.figma.com/design/wZAiODRsAfqa8cAxJtQAYr/Untitled?node-id=0-1&t=jbtVtLENKlvQoKjX-1
