### ISSUE TITLE
Give users the ability to send multiple picture at once

### ISSUE THREAD

**Issue by Youllou** [ai-cfia/fertiscan-frontend#30]
## Description :
Add a file list giving the users the ability to send multiple picture at once

## Tasks :
 - [x] Add a picture list that shows each added picture
 - [x] Make it possible to delete a picture from the list
 -  ~~Merge all picture in one before sending it~~ (backend manage multiple files)

## Acceptance Criteria :
- [x] The pictures are easy to manage
- [x] Selecting multiple pictures in the file opener makes all pictures available in the list
- [x] Clicking on submit sends one request to the upload backend endpoint for each file then one request to the analyze endpoint

**Comment by Youllou** [comment]
Closed in #34
