### ISSUE TITLE
As a dev, I want my application to only accept image files (png, jpg, ...) in the file selector.

### ISSUE THREAD

**Issue by Youllou** [ai-cfia/fertiscan-frontend#31]
## Description :
Make sure only picture type media can be send via the application

## Tasks :
 - [x] Change file input so it accept only picture like media
 - [x] Prompt an error if the user wants to add a non picture like media

## Acceptance Criteria :
- [x] A file that is not accepted by the backend cant be sent to the backend.
- [x] The user knows why the action he just did hasn't worked.
- [x] Any file accepted by the backend can be added through the file input.
