### ISSUE TITLE
Fix workflow and lint errors

### ISSUE THREAD

**Issue by Youllou** [ai-cfia/fertiscan-frontend#43]
## Description :
Right now almost none of the github workflow tests passes. Those issues also affects the build of the application
All those errors must be corrected for the application to build and be deployed.

## Tasks :
 - [ ] Make sure lint tests passes
 - [ ] Run prettier
 - [ ] Make sure all worflow tests passes

## Acceptance Criteria :
- [ ] No warning nor error is prompted when running `npm run lint` command
- [ ] All worflows tests passes
- [ ] The project can be built and deployed

**Comment by Francois-Werbrouck** [comment]
Fixed in a previous issues for BE and FE
