### ISSUE TITLE
Add progress bar that show approved and modify textarea

### ISSUE THREAD

**Issue by SamuelPelletierEvraire** [ai-cfia/fertiscan-frontend#45]
## Description
As the user must approve all textarea, they should also be able to see how they are progressing.

## Tasks
- [ ] Design a progress bar that shows how much of the field has been verified
- [ ] Make so each non completed field are easely identified with the progress bar
- [ ] Make a link between the progress bar steps and the corresponding fields so the user can navigate through the fields using the progress bar

## Acceptance criteria
- [ ] It is easy to know which fields are yet to be validated
- [ ] It is possible to navigate through the fields using the progress bar
- [ ] The progress bar is synced to the fields completion

**Comment by SamuelPelletierEvraire** [comment]
Duplicated
