### ISSUE TITLE
Adding button modify and approve on form page.

### ISSUE THREAD

**Issue by SamuelPelletierEvraire** [ai-cfia/fertiscan-frontend#46]
## Description
The user should validate each field of the resulting data and be able to modify a field if it was incorrect.

## Tasks
- [ ] Add a button to validate a field when it corresponds to the fertiliser label
- [ ] Add a way to modify a field if it is wrong

## Acceptance criteria
- [ ] When a field is validated it can not be modified 
- [ ] Modifying a field require a clear action from the user
- [ ] A field cant be modified by accident
