### ISSUE TITLE
Adding confirmation page.

### ISSUE THREAD

**Issue by SamuelPelletierEvraire** [ai-cfia/fertiscan-frontend#47]
## Description
Once the user has validated all fields in the formPage, they must be able to re-read all the fields and validate one last time before sending the data to the database

## Tasks
- [x] Create a `send` button that is unlocked once all fields are validated
- [ ] Create a page that prompts all the validated data to the user
- [x] Show the page when the `send` button is clicked
- [ ] Create two buttons in the new page, one to `confirm` one to `cancel`

## Acceptance criteria
- [x] The `send` button is locked until all fields are validated
- [ ] The data on the new page cant be modified
