### ISSUE TITLE
Adding sub-menu to all page.

### ISSUE THREAD

**Issue by SamuelPelletierEvraire** [ai-cfia/fertiscan-frontend#48]
## Description
Add a sidenav menu so the user can navigate through the application

## Tasks
- [x] Create a SideNav menu with links to different pages
- [x] Create a hamburger button to open the SideNav menu

## Acceptance criteria
- [x] The home page is accessible from the menu
- [x] The form page is NOT accessible from the menu
- [x] The user can access the login page
- [x] All layout are not broken by the side nav
