### ISSUE TITLE
Add login page.

### ISSUE THREAD

**Issue by SamuelPelletierEvraire** [ai-cfia/fertiscan-frontend#50]
## Description
Add a login page so the user can access to the application. 
After this issue is done, the login shall be mandatory to access the application

## Tasks
- [ ] Create a login page where the user should enter a username/mail and a password
- [ ] Create a way to authentify a connected user (probably JWT)
- [ ] Make sure a non authentified user cant access the formpage
- [ ] Make a function to redirect the user to the login page when they try to send a picture

## Acceptance criteria
- [ ] The formPage is not accessible if not authentified
- [ ] When the user try to upload a file but isnt authentified, they are redirected to the login page
- [ ] When the user login after being redirected from uploading, the user is redirected to the formpage with the picture uploaded
