### ISSUE TITLE
Add modal to tell user when a fertiliser is already register.

### ISSUE THREAD

**Issue by SamuelPelletierEvraire** [ai-cfia/fertiscan-frontend#52]
## Description
When a user scann a label that was previously registered, the user shall know that the fertiliser exists in the database

## Tasks 
- [ ] Check if the label exists in the database (use futur api route)
- [ ] Prompt a message to the user if the label exists
- [ ] Still prompt the formpage (later the user will be able to validate the current label with what is stored in the database)

## Acceptance criteria
- [ ] If the label doesnt exists in the database the user is not prompted the message
- [ ] The user has still access to the formpage after that
