### ISSUE TITLE
Add my registration page.

### ISSUE THREAD

**Issue by SamuelPelletierEvraire** [ai-cfia/fertiscan-frontend#55]
## Depends on
- #50 

## Description
Add a page that shows all the user registration/upload

## Tasks
- [ ] Create a page that lists all user registration/upload (potentially the same as #56 )
- [ ] Give access to this page only when the user is connected
- [ ] Give the user the ability to click on a registration o

## Acceptation criteria
- [ ] This page is accessible only when connected
- [ ] All and only the user's registration are listed
