### ISSUE TITLE
Add search fertiliser page.

### ISSUE THREAD

**Issue by SamuelPelletierEvraire** [ai-cfia/fertiscan-frontend#56]
## Depends on
- ai-cfia/fertiscan-backend#48
- #50 

## Description
Add a page so a connected user can search for a fertiliser

## Tasks
- [ ] Create a SearchPage 
- [ ] Send a search request to the backend
- [ ] Prompt the search result
- [ ] Create a page that prompts a specific fertiliser

## Acceptance criteria
- [ ] The search is efficient and quick 
- [ ] If no great enough result has been found a message is shown to the user saying that the fertiliser havent been uploaded
