### ISSUE TITLE
Add admin page.

### ISSUE THREAD

**Issue by SamuelPelletierEvraire** [ai-cfia/fertiscan-frontend#59]
## Depends on
- #50 

## Description
Add an admin page to have some controls on the database

## Tasks
- [ ] Create an admin page
- [ ] Make the page accessible only to admin
- [ ] Give controls on the database to the admin user

## Acceptance criteria
- [ ] The admin page is accessible only through admin accounts
