### ISSUE TITLE
Fix react strict mode to avoid double request to backend

### ISSUE THREAD

**Issue by Youllou** [ai-cfia/fertiscan-frontend#61]
## Description
When in Strict mode, react render twice so the useEffect Hook is called twice too.
We dont want to have two concurent request to the backend as it create issues.

## Tasks
- [ ] Deactivate StrictMode from the root
- [ ] Activate StrictMode on compnents that are not linked with the backend

## Acceptance criteria 
- [ ] Only one request is sent to the backend
- [ ] Components are still affected by StrictMode to ensure error verification
