### ISSUE TITLE
Make the application statefull

### ISSUE THREAD

**Issue by Youllou** [ai-cfia/fertiscan-frontend#93]
# Description 
make the apllication statefull so a user is not forced to start from the beginning if he change pages

# Tasks
- [ ] Implement a session wide variable that keeps the state of the user progression
- [ ] Save the state of the user whenever he quits the main workflow
- [ ] Return to the state whenever the user goes back to the main workflow
