### ISSUE TITLE
Implement a session wide variable that represents the state of the application

### ISSUE THREAD

**Issue by Youllou** [ai-cfia/fertiscan-frontend#94]
# Description
To make the application statefull we need a way to keep track of the state of the apllication. The state of a tab should not impact the state of an other tab, hence the `session wide`. 

# Tasks
- [ ] Create a session variable.
- [ ] Store the state of the application in it

# Acceptance criteria
- [ ] Each time the state is modified, the session variable should be modified accordingly.
- [ ] If the state of tab is modified, the state of another tab should not be modified
