### ISSUE TITLE
Modify the routing logic so all 3 steps of the main workflow are on /

### ISSUE THREAD

**Issue by Youllou** [ai-cfia/fertiscan-frontend#95]
# Description
The user should acces those page only from its current state not from the url

# Tasks 
- [ ] Rename HomePage to CapturPage
- [ ] Create a new HomePage that retrieves the state and prompt the correct page accordingly

# Acceptance criteria
- [ ] The workflow is still working
- [ ] Given the state, the HomePage prompts the correct page
